[[headers]]
for = "/*"
[headers.values]
Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com data:; img-src 'self' data: https: *; connect-src 'self' https://api.github.com https://newsapi.org; frame-src 'self' https://www.youtube.com https://youtube.com https://www.youtube-nocookie.com; object-src 'none'; base-uri 'self';"

[build]
command   = "npm run build"
publish   = "dist"
functions = "netlify/functions"

[dev]
command       = "npm run dev"
targetPort    = 5173
port          = 8888
functionsPort = 9999